# Generated by Django 4.0 on 2022-04-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_question_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
