# Generated by Django 4.0 on 2022-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
