# Generated by Django 4.0 on 2022-04-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
