# Generated by Django 4.0 on 2022-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
