# Generated by Django 4.0 on 2022-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
