# Generated by Django 4.0 on 2022-04-06 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0016_alter_answer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
