# Generated by Django 4.0 on 2022-04-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='code',
        ),
    ]
